### ISSUE TITLE
Heatmap height too small in docs

### ISSUE THREAD

**Issue by jakob-stoeck** [frappe/charts#12]
https://github.com/frappe/charts/blob/4bb44c0914125e4b511592623870946bdac3f0a8/docs/index.html#L218

It’s hiding the seventh day each week. Should be 115px.

**Comment by achillesrasquinha** [comment]
Send in a PR!

**Comment by pratu16x7** [comment]
@jakob-stoeck The PR for this small change would be as easy as editing the file on GitHub itself :)

**Comment by iDemonix** [comment]
I came here to mention this, the 115px height fixed it.

On a possibly related note, I don't appear to see today, or any days since the 27th, it appears to be the same on [https://frappe.github.io/charts/](https://frappe.github.io/charts/)

![image](https://user-images.githubusercontent.com/3519214/32299248-d8e90156-bf4c-11e7-8042-869dd8c6c4ba.png)

Also, it'd be good to see some actual data behind the heatmap on [https://frappe.github.io/charts/](https://frappe.github.io/charts/) as it's the only chart that has no data, despite the heatmap_data variable being populated in your index.js file. I'm struggling to get it to show data, but it seems this way on your site too?
