### ISSUE TITLE
Support IE 11

### ISSUE THREAD

**Issue by chintan9** [frappe/charts#13]
It simply does not work IE 11.  How can I support this library with IE11(polyfills or anything else)

**Comment by sakopov** [comment]
IE 11 doesn't support ES6. I don't think there is much you could do here.

**Comment by chintan9** [comment]
![capturfiles](https://user-images.githubusercontent.com/1642564/32292376-01346428-bf0e-11e7-80db-c2b4a8b7f642.png)

**Comment by pratu16x7** [comment]
@chintan9 Could you elaborate on your changes? It's tough to make out from the build file.

**Comment by chintan9** [comment]
@pratu16x7 Simply I decomplie you code to es6 (es2015) level and add polyfills for ie11.

**Comment by pratu16x7** [comment]
Please feel free to make the specific polyfill changes in the `src` files and reopen the PR :)
Closing this for now.

**Comment by achillesrasquinha** [comment]
How about adding the polyfill into our `src/scripts` to make this simpler? Closing this for now. Please feel free to reopen.

**Comment by pratu16x7** [comment]
Will have to agree with @sakopov. About polyfills, from https://babeljs.io/docs/usage/polyfill:
`This will emulate a full ES2015+ environment and is intended to be used in an application rather than a library/tool.`

We don't intend to go that way; that'd defeat the zero-dep purpose. We'd be happy if there is a more elegant way to achieve this. Closing for now.

**Comment by chintan9** [comment]
@pratu16x7 Transpile  whole lib to es5 would be solution
